### PR TITLE
fix new line bug for paragraphs

### LINKED ISSUE #26: Newline should not create a new HTML paragraph
The paragraph marking style in org is the same as in markdown.

If I have 

```
abcd
efgh

ijkl
mnop
```

it should export to HTML as

```html
<p>
abcd
efgh
</p>

<p>
ijkl
mnop
</p>
```

But instead, it is currently creating a paragraph for each new line.

---

This is the expected behavior:

- A single newline does not end a paragraph.
- Two or more consecutive newlines end a paragraph (basically one ore more blank lines).

--- 

I found this issue because I like to enable `auto-fill-mode` for my posts with `fill-column` set to 70 in emacs.

### PR DESCRIPTION
**Pull request by chaseadamsio**
fixes #26

### CODE REVIEW

**Comment by kaushalmodi** [comment]
Thanks for working on this. I tried it out and I found an issue with this example:

```
* Start a new paragraph
An empty line starts a new paragraph.
#+BEGIN_SRC text
/Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo
ligula nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque
eu, sem. Nulla consequat massa quis enim./

/In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam
dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus
elementum semper nisi./
#+END_SRC
/Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, sem. Nulla consequat massa quis enim./

/In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi./
```

While the paragraph break detection is fixed, it renders the HTML incorrectly around this part:

```
An empty line starts a new paragraph.
#+BEGIN_SRC text
```

I get the expected HTML only if I have a newline between those 2 lines:
```
An empty line starts a new paragraph.

#+BEGIN_SRC text
```

---

For the example in the beginning of this post, the HTML is:

```html
<h2 id="start-a-new-paragraph">Start a new paragraph</h2>

<p>An empty line starts a new paragraph.

/Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo
ligula nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque
eu, sem. Nulla consequat massa quis enim.</p>
<div class="highlight" style="background: #ffffff"><pre style="line-height: 125%"><span></span>/In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam
dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus
elementum semper nisi./
</pre></div>

<p><em>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, sem. Nulla consequat massa quis enim.</em></p>

<p><em>In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi.</em></p>
```

---

With that extra newline above `#+BEGIN_SRC text`, the HTML is:

```html
<h2 id="start-a-new-paragraph">Start a new paragraph</h2>

<p>An empty line starts a new paragraph.</p>
<div class="highlight" style="background: #ffffff"><pre style="line-height: 125%"><span></span>/Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo
ligula nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque
eu, sem. Nulla consequat massa quis enim./

/In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam
dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus
elementum semper nisi./
</pre></div>

<p><em>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, sem. Nulla consequat massa quis enim.</em></p>

<p><em>In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi.</em></p>
```

---

## Summary

The extra newline should not be needed above org-mode special comment lines or any comment line like `#+BEGIN_SRC text` or `# foo`.

Org-mode auto-creates a paragraph after comment lines ([Reference](https://lists.gnu.org/archive/html/emacs-orgmode/2016-08/msg00276.html)).

**Comment by chaseadamsio** [comment]
Makes sense. I'll add the case and fix it today.

**Comment by chaseadamsio** [comment]
@kaushalmodi I just did an org-export on the code you shared and this is what org exports (org-version 9.0.5):

```

<h2 id="org487e5fd">Start a new paragraph</h2>
<div class="outline-text-2" id="text-1">
<p>
An empty line starts a new paragraph.
</p>
<div class="org-src-container">
<pre class="src src-text">/Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo
ligula nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque
eu, sem. Nulla consequat massa quis enim./

/In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam
dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus
elementum semper nisi./
</pre>
</div>
<p>
<i>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, sem. Nulla consequat massa quis enim.</i>
</p>

<p>
<i>In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi.</i>
</p>
</div>
```

aside from the class names and ids, the output looks like the same html to me as what I get when I do an export with goorgeous:

```

```
                <h2 id="start-a-new-paragraph">Start a new paragraph</h2>
		
		<p>An empty line starts a new paragraph.</p>
		
		<pre><code class="language-text">
		/Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo
		ligula nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque
		eu, sem. Nulla consequat massa quis enim./
		
		/In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam
		dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus
		elementum semper nisi./
		</code></pre>
		
		<p><em>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, sem. Nulla consequat massa quis enim.</em></p>
		
		<p><em>In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi.</em></p>
```

What am I missing?

**Comment by chaseadamsio** [comment]
@kaushalmodi the output isn't verbatim, but the expected html now matches. I've added a test case for your text with slightly modified output. Please take a look.

**Comment by kaushalmodi** [comment]
I confirm the fix! Thanks.

**Pull request merged**
